### PR TITLE
Trying to build on JDK 11

### PR DESCRIPTION
**Pull request by jglick**
First problem was that `javax.annotation.*` is gone.

Bigger problem is

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/javac/file/ZipArchive
	at com.cloudbees.groovy.cps.tool.Driver.run(Driver.java:48)
	at com.cloudbees.groovy.cps.tool.Driver.main(Driver.java:28)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.file.ZipArchive
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```

which is not solved by

```bash
--add-exports jdk.compiler/com.sun.tools.javac=ALL-UNNAMED
```

(Maybe not right; just Googling for solutions.)

But using Shade does not work either:

```
Exception in thread "main" java.lang.NullPointerException
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:148)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:133)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations.access$000(Locations.java:70)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:616)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:642)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.getLocation(Locations.java:576)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.Locations.getLocation(Locations.java:677)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:803)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:617)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2732)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2428)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:244)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:845)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Resolve.findType(Resolve.java:2042)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Resolve.findIdent(Resolve.java:2071)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr$IdentAttributer.visitIdentifier(Attr.java:421)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr$IdentAttributer.visitIdentifier(Attr.java:403)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
	at com.cloudbees.groovy.cps.com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:406)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:403)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.cloudbees.groovy.cps.com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:406)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:403)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:399)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.main.JavaCompiler.resolveIdent(JavaCompiler.java:708)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:125)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:108)
	at com.cloudbees.groovy.cps.com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:61)
	at com.cloudbees.groovy.cps.tool.Translator.<init>(Translator.java:159)
	at com.cloudbees.groovy.cps.tool.Driver.run(Driver.java:61)
	at com.cloudbees.groovy.cps.tool.Driver.main(Driver.java:28)
```

### CODE REVIEW

**Review by dwnusbaum — COMMENTED** [review]
Personally, as far as short term options, I think it would probably be simpler to extract `dgm-builder` as it exists now to a separate repository along with a new `cps-stdlib` module that would actually generate the sources. We would only need to release new versions using Java 8 when we update Groovy, which doesn't happen very often.

I would also be fine with extracting `dgm-builder` as-is, inlining the current generated sources into `groovy-cps` and just declaring that `CpsDefaultGroovyMethods` is effectively frozen against Groovy 2.4.21.

> Exception in thread "main" java.lang.NullPointerException

This is because the `sun.boot.class.path` system property was removed in Java 9. It looks like you can get things working by explicitly passing `-Dsun.boot.class.path=...` (I tested by _running_ Java 17 but passing classes and jars from a Java 8 JDK to `sun.boot.class.path`).

Running `dgm-builder` using Java 9+ and specifying a `sun.boot.class.path` that contains classes for that same JDK is somewhat awkward, since JDK classes are now packaged in `.jmod` files, so you cannot directly add them to `sun.boot.class.path`. You could probably get things working with `jmod extract` with some effort.

That said, trying to run Java 8's `javac` against Java 9+ seems fragile and I suspect it would end up breaking again in the future anyway. I think the best option would be to abandon `sorcerer-javac` and rewrite `dgm-builder` using some other library like ASM.

**Comment by jglick** [comment]
> extract `dgm-builder` as it exists now to a separate repository

That would make it harder to work on. I think we should be moving in the direction of consolidating, even making all of this submodules of `workflow-cps-plugin`.

> trying to run Java 8's `javac` against Java 9+ seems fragile

Indeed. I think what we should actually do is convert this tool to JMS and import `java.compiler` + `jdk.compiler` properly.

**Comment by dwnusbaum** [comment]
> That would make it harder to work on. I think we should be moving in the direction of consolidating, even making all of this submodules of workflow-cps-plugin.

For `lib/`, sure, but the last change to `dgm-builder/` that actually modified the generated sources was https://github.com/cloudbees/groovy-cps/pull/85 in 2019, and I see no reason to believe that the frequency of changes would increase in the future, so I think that making it easier to work with `lib/` at the cost of making it more difficult to work with `dgm-builder` is an acceptable tradeoff.

> I think what we should actually do is convert this tool to JMS and import java.compiler + jdk.compiler properly.

Yeah, I looked into that (along with shading) back in 2020, see https://github.com/jenkinsci/workflow-cps-plugin/pull/360#issuecomment-639534048, but I could not manage to get `Driver` working with Java 11. It might be easier if we can drop support for Java 8, but I am not familiar with the APIs in those modules, so IDK. Maybe you would be able to get things working without too much effort though.

**Comment by jglick** [comment]
> It might be easier if we can drop support for Java 8

At this point we could certainly do so.

**Comment by dwnusbaum** [comment]
See https://github.com/cloudbees/groovy-cps/pull/120, which I plan to finalize in the next week or so.

**Pull request closed without merging**
