### PR TITLE
[JENKINS-26481] Generate CpsDefaultGroovyMethods, invoke using GroovyCategorySupport

### PR DESCRIPTION
**Pull request by jglick**
I accidentally merged #54 and it seems GitHub offers no way to unmerge a PR.

Pulls the category trick down from jenkinsci/workflow-cps-plugin#124 (and should become upstream of that if all works out).

Implements #7, picking up artifacts from cloudbees/groovy-cps-dgm-builder#4 (ideally this would be automated by Maven but for now it is manual).

Supersedes #52 (though the expanded tests could be sideported).

@reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
I was wondering what happened there...

**Comment by jglick** [comment]
Well I do not know how to implement `sort` so my feeling is that if @kohsuke wants to take it on some time, great, else we do not do it. (It would have been easier had the translation tool been written to reuse `CpsTransformer`, treating its Java input as Groovy code except in special cases like new arrays with initializers, but instead it is a separate beast, and quite hard to work on.)

W.r.t. `StringGroovyMethods`, if you feel like writing a test for it now, I should be able to include it pretty easily (if all goes well), but I am guessing it is rarely used so I was not going to hold things up for that.

**Comment by abayer** [comment]
Ok, sounds reasonable on both counts.

**Comment by jglick** [comment]
@reviewbybees done

**Pull request merged**
