### PR TITLE
Fix #8: ArrayList.each method dispatch is buggy

### LINKED ISSUE #8: ArrayList.each method dispatch is buggy
`Sequence.each` correctly dispatches to `CpsDefaultGroovyMethods.each`, but somehow `ArrayList.each` isn't dispatching to that method. Instead, it finds `DefaultGroovyMethods.each`.

Presumably the way we register `CpsDefaultGroovyMethods` methods into Groovy runtime is incorrect, and the method dispatch cache for `ArrayList` contains stale entry.

To fix this issue, either figure out how to insert meta-method into Groovy, or figure out how to clean up stale cache.

### PR DESCRIPTION
**Pull request by jglick**
Fixing #8.

### CODE REVIEW

**Comment by jglick** [comment]
`each` and `eachArray` both call

```
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:69)
com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:100)
com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:76)
sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:25)
com.cloudbees.groovy.cps.Next.step(Next.java:58)
com.cloudbees.groovy.cps.Next.run(Next.java:49)
com.cloudbees.groovy.cps.Next$run.call
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
com.cloudbees.groovy.cps.AbstractGroovyCpsTest.evalCPSonly(AbstractGroovyCpsTest.groovy:55)
com.cloudbees.groovy.cps.AbstractGroovyCpsTest.evalCPS(AbstractGroovyCpsTest.groovy:49)
com.cloudbees.groovy.cps.AbstractGroovyCpsTest$evalCPS.callCurrent
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
```

But then `each` calls

```
com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods.groovy:44)
sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:51)
org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
```

whereas `eachArray` calls

```
org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1351)
org.codehaus.groovy.runtime.dgm$170.invoke
```

**Comment by jglick** [comment]
Finally I know why my original attempt to create a test for #6 failed. If you make this innocent-seeming change:

```diff
diff --git a/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy b/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
index 4ef504e..4ee2dbe 100644
--- a/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
+++ b/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
@@ -46,8 +46,9 @@ abstract class AbstractGroovyCpsTest extends Assert {
     }
 
     Object evalCPS(String script) {
+        Object ov = sh.evaluate(script);
         Object v = evalCPSonly(script)
-        assert v==sh.evaluate(script); // make sure that regular non-CPS execution reports the same result
+        assert v == ov; // make sure that regular non-CPS execution reports the same result
         return v;
     }
 
```

then you get a similar failure:

```
$ mvn test -Dtest=CpsTransformerTest\#each
…
each(com.cloudbees.groovy.cps.CpsTransformerTest)  Time elapsed: 0.72 sec  <<< FAILURE!
Assertion failed: 

assert v == ov
       | |  |
       0 |  55
         false
```

demonstrating that there is a cache effect.

**Comment by jglick** [comment]
So the following works, confirming that this is all a problem of timing of registration vs. evaluation of non-CPS Groovy code:

```diff
diff --git a/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java b/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
index 105f3ad..4c9f287 100644
--- a/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
+++ b/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
@@ -32,7 +32,7 @@ import static com.cloudbees.groovy.cps.impl.SourceLocation.*;
  * @see ContinuationPtr
  * @author Kohsuke Kawaguchi
  */
-abstract class ContinuationGroup implements Serializable {
+public abstract class ContinuationGroup implements Serializable {
     public Next then(Block exp, Env e, ContinuationPtr ptr) {
         return new Next(exp,e,ptr.bind(this));
     }
@@ -103,7 +103,7 @@ abstract class ContinuationGroup implements Serializable {
 */
     }
 
-    static {
+    public static void register() {
         for (CachedMethod m : ReflectionCache.getCachedClass(CpsDefaultGroovyMethods.class).getMethods()) {
             CachedClass[] paramTypes = m.getParameterTypes();
             if (paramTypes.length>0)
diff --git a/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy b/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
index 8f1ab2f..9c354f6 100644
--- a/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
+++ b/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
@@ -13,6 +13,11 @@ import org.junit.Before
  * @author Kohsuke Kawaguchi
  */
 abstract class AbstractGroovyCpsTest extends Assert {
+
+static {
+com.cloudbees.groovy.cps.impl.ContinuationGroup.register();
+}
+
     /**
      * CPS-transforming shelll
      */
diff --git a/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy b/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
index 74e972b..d08d0ce 100644
--- a/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
+++ b/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
@@ -411,7 +411,6 @@ class CpsTransformerTest extends AbstractGroovyCpsTest {
 """) == 55;
     }
 
-    @Ignore("TODO #8: expected 6 but was 1")
     @Test
     void eachArray() {
         assert evalCPS("""
```

**Comment by jglick** [comment]
The `MetaClassImpl` for `ArrayList` has a `MetaMethodIndex` that lists `each` from `dgm$170`.

**Comment by jglick** [comment]
`MetaClassImpl.dropMethodCache("each")` did not work, I think because this clears `cachedMethod` but not `methods` (?). `MetaClassImpl.metaMethodIndex.clear()` broke everything. I would prefer to just get rid of the `MetaClassImpl` altogether, but `ClassInfo.globalClassSet` is not a `java.util.Map` and lacks any `clear` method.

**Comment by jglick** [comment]
The `each` test (run on its own) is still broken. `remove(Sequence.class)` does not seem to work, investigating.

**Comment by jglick** [comment]
Ugly as sin but the best I have managed so far. @reviewbybees

**Comment by kohsuke** [comment]
`DefaultGroovyMethods` are build-time processed (where?) to a series of "dgm" classes, and this gets loaded into `MetaClass` structures in `GeneratedMetaMethod.DgmMethodRecord.loadDgmInfo()`.

**Comment by kohsuke** [comment]
`ExpandoMetaClass` seems to allow programs to dynamically add/remove methods to a class ([see here](http://groovy.codehaus.org/ExpandoMetaClass)). How does this work?

This is handled in `ExpandoMetaClass.setProperty(String,Object)`, and gets eventually added via `ExpandoMetaClass.registerInstanceMethod()`.

**Comment by kohsuke** [comment]
When you drop `ClassInfo` from `ClassInfoSet` like the proposal, I think this will also drop all the DGM methods declared specifically for that receiver type (and maybe even other expando meta methods added?)

The other problem is that the fix critically depends on what `ClassInfo` is already loaded, and in applications like Jenkins workflow, this is unpredictable.

**Comment by kohsuke** [comment]
I have to think about how to do this. Maybe there's a different approach, such as the use of category, which was how it was done in the beginning.

**Comment by jglick** [comment]
It is documented that `ExpandoMetaClass` does not do inheritance; there is a global static flag (ick!!) to enable that. Anyway I have not managed to make that system override `DefaultGroovyMethods` methods.

**Comment by oleg-nenashev** [comment]
@jglick 
Are you waiting for the request? I suppose the most of the bees cannot contribute much to the this discussion between you and KK

**Comment by rsandell** [comment]
:bee: from the few insights I grasped from the discussion.

**Comment by jglick** [comment]
Last I checked @kohsuke was uncomfortable with this fix. Anyway it deserves a downstream "integration test" in `workflow-plugin`.

**Comment by jglick** [comment]
> `DefaultGroovyMethods` are build-time processed (where?)

Sounds like #7.

**Comment by jglick** [comment]
Superseded.

**Pull request closed without merging**
